### ISSUE TITLE
imgui_runner crash g.IO.KeyMap out of bounds 

### ISSUE THREAD

**Issue by MaKiPL** [pthom/imgui_datascience#87]
* ImGui
* Python version: 3.8.9
* Operating System: MacOS 

### Description

```py
/Users/marcingomulak/PycharmProjects/pythonProject/venv/bin/python /Users/marcingomulak/PycharmProjects/pythonProject/main.py
pygame 2.1.2 (SDL 2.0.18, Python 3.8.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/marcingomulak/PycharmProjects/pythonProject/main.py", line 24, in <module>
    im.imgui_runner.run(gui_loop, parm)
  File "/Users/marcingomulak/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/imgui_datascience/imgui_runner.py", line 77, in run
    imgui.new_frame()
  File "imgui/core.pyx", line 1867, in imgui.core.new_frame
imgui.core.ImGuiError: ImGui assertion error (g.IO.KeyMap[n] >= -1 && g.IO.KeyMap[n] < IM_ARRAYSIZE(g.IO.KeysDown) && "io.KeyMap[] contains an out of bound value (need to be 0..512, or -1 for unmapped key)") at imgui-cpp/imgui.cpp:3097
```

### What I Did

```py
def gui_loop():
    im.text("text")


parm = im.imgui_runner.Params(
    win_size=(640, 480),
    win_title="SAMPLE",
    windowed_full_screen=False)
im.imgui_runner.run(gui_loop, parm)
```

Although I'm unsure if it's not imgui error itself or if it's tied to imgui_runner

**Comment by pthom** [comment]
Hello,

I think you are experiencing this issue: https://github.com/pyimgui/pyimgui/issues/210
It is fixed in branch `dev/version-2.0` of pygame (see https://github.com/pyimgui/pyimgui/issues/210#issuecomment-1036571753)


So the basic answer is to install pyimgui this way: 
````
pip install git+https://github.com/pyimgui/pyimgui.git@dev/version-2.0
````

On this repo, the merged [PR](https://github.com/pthom/imgui_datascience/pull/86)  make imgui_datascience compatible with pyimgui's branch `dev/version-2.0`.


I just pushed a commit that modify requirements.txt. Can you tell me if it works for you?

**Comment by pthom** [comment]
Oops, I,had closed too quickly

**Comment by pthom** [comment]
The fix works. Closing this issue
